using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using ReflectionUtility;
using HarmonyLib;
using System.Reflection;

namespace AmbientWar
{
    class attacks
    {
        public static void init()
        {
			
		    ItemAsset WagonBala = AssetManager.items.clone("WagonBala", "_range");
            WagonBala.id = "WagonBala";
            WagonBala.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            WagonBala.materials = new List<string> { "iron" };
            WagonBala.projectile = "Bala";
            WagonBala.base_stats[S.fertility] = -1f;
            WagonBala.base_stats[S.max_children] = 0f;
            WagonBala.base_stats[S.max_age] = 0f;
            WagonBala.base_stats[S.attack_speed] = 0f;
            WagonBala.base_stats[S.damage] = 0;
            WagonBala.base_stats[S.speed] = 0f;
            WagonBala.base_stats[S.health] = 0;
            WagonBala.setCost(1, "iron", 1);
            WagonBala.base_stats[S.accuracy] = 0;
            WagonBala.base_stats[S.range] = 0;
            WagonBala.quality = ItemQuality.Legendary;
            WagonBala.equipment_value = 89999;
            WagonBala.tech_needed = "Siegeweapons";
            WagonBala.equipmentType = EquipmentType.Weapon;
            WagonBala.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(WagonBala);
            Localization.addLocalization("item_WagonBala", "WagonBala");
			
		    ItemAsset RobotGunBa = AssetManager.items.clone("RobotGunBa", "_range");
            RobotGunBa.id = "RobotGunBa";
            RobotGunBa.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            RobotGunBa.materials = new List<string> { "iron" };
            RobotGunBa.projectile = "LaserBlueSmall4";
            RobotGunBa.base_stats[S.fertility] = -1f;
            RobotGunBa.base_stats[S.max_children] = 0f;
            RobotGunBa.base_stats[S.max_age] = 0f;
            RobotGunBa.base_stats[S.attack_speed] = 0f;
            RobotGunBa.base_stats[S.damage] = 10;
            RobotGunBa.base_stats[S.speed] = 0f;
            RobotGunBa.base_stats[S.health] = 0;
            RobotGunBa.setCost(1, "iron", 1);
            RobotGunBa.base_stats[S.accuracy] = 0;
            RobotGunBa.base_stats[S.range] = 0;
            RobotGunBa.quality = ItemQuality.Legendary;
            RobotGunBa.equipment_value = 89999;
            RobotGunBa.tech_needed = "Siegeweapons";
            RobotGunBa.equipmentType = EquipmentType.Weapon;
            RobotGunBa.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(RobotGunBa);
            Localization.addLocalization("item_RobotGunBa", "RobotGunBa");
			
		    ItemAsset OVABala = AssetManager.items.clone("OVABala", "_range");
            OVABala.id = "OVABala";
            OVABala.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            OVABala.projectile = "OVArEProt4";
            OVABala.quality = ItemQuality.Legendary;
            OVABala.equipment_value = 89999;
            OVABala.tech_needed = "Sub_Robots";
            OVABala.equipmentType = EquipmentType.Weapon;
            OVABala.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(OVABala);
            Localization.addLocalization("item_OVABala", "OVABala");
			
			ItemAsset mortarAtt = AssetManager.items.clone("mortarAtt", "_range");
            mortarAtt.id = "mortarAtt";
            mortarAtt.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            mortarAtt.materials = new List<string> { "iron" };
            mortarAtt.projectile = "mortarP4";
            mortarAtt.base_stats[S.fertility] = -1f;
            mortarAtt.base_stats[S.max_children] = 0f;
            mortarAtt.base_stats[S.max_age] = 0f;
            mortarAtt.base_stats[S.attack_speed] = -20f;
            mortarAtt.base_stats[S.damage] = 0;
            mortarAtt.base_stats[S.speed] = 0f;
            mortarAtt.base_stats[S.health] = 0;
            mortarAtt.setCost(1, "gold", 2);
            mortarAtt.base_stats[S.accuracy] = 0;
            mortarAtt.base_stats[S.range] = 0;
            mortarAtt.quality = ItemQuality.Legendary;
            mortarAtt.equipment_value = 89999;
            mortarAtt.tech_needed = "Siegeweapons";
            mortarAtt.equipmentType = EquipmentType.Weapon;
            mortarAtt.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(mortarAtt);
            Localization.addLocalization("item_mortarAtt", "mortarAtt");
			
			ItemAsset TrabuchetAtt = AssetManager.items.clone("TrabuchetAtt", "_range");
            TrabuchetAtt.id = "TrabuchetAtt";
            TrabuchetAtt.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            TrabuchetAtt.materials = new List<string> { "iron" };
            TrabuchetAtt.projectile = "TrabuchetP4";
            TrabuchetAtt.base_stats[S.fertility] = -1f;
            TrabuchetAtt.base_stats[S.max_children] = 0f;
            TrabuchetAtt.base_stats[S.max_age] = 0f;
            TrabuchetAtt.base_stats[S.attack_speed] = -20f;
            TrabuchetAtt.base_stats[S.damage] = 0;
            TrabuchetAtt.base_stats[S.speed] = 0f;
            TrabuchetAtt.base_stats[S.health] = 0;
            TrabuchetAtt.setCost(1, "gold", 2);
            TrabuchetAtt.base_stats[S.accuracy] = 0;
            TrabuchetAtt.base_stats[S.range] = 0;
            TrabuchetAtt.quality = ItemQuality.Legendary;
            TrabuchetAtt.equipment_value = 89999;
            TrabuchetAtt.tech_needed = "Siegeweapons";
            TrabuchetAtt.equipmentType = EquipmentType.Weapon;
            TrabuchetAtt.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(TrabuchetAtt);
            Localization.addLocalization("item_TrabuchetAtt", "TrabuchetAtt");
			
			ItemAsset Jet01Att = AssetManager.items.clone("Jet01Att", "_range");
            Jet01Att.id = "Jet01Att";
            Jet01Att.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Jet01Att.materials = new List<string> { "iron" };
            Jet01Att.projectile = "Jet01Proye4";
            Jet01Att.base_stats[S.fertility] = 0f;
            Jet01Att.base_stats[S.max_children] = 0f;
            Jet01Att.base_stats[S.max_age] = 0f;
            Jet01Att.base_stats[S.attack_speed] = 0f;
            Jet01Att.base_stats[S.damage] = 0;
            Jet01Att.base_stats[S.speed] = 0f;
            Jet01Att.base_stats[S.health] = 0;
            Jet01Att.setCost(1, "gold", 1);
            Jet01Att.base_stats[S.accuracy] = 0;
            Jet01Att.base_stats[S.range] = 0;
            Jet01Att.quality = ItemQuality.Legendary;
            Jet01Att.equipment_value = 89999;
            Jet01Att.tech_needed = "Siegeweapons";
            Jet01Att.equipmentType = EquipmentType.Weapon;
            Jet01Att.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Jet01Att);
            Localization.addLocalization("item_Jet01Att", "Jet01Att");
			
            ItemAsset Cannon = AssetManager.items.clone("Cannon", "_range");
            Cannon.id = "Cannon";
            Cannon.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Cannon.materials = new List<string> { "iron" };
            Cannon.projectile = "Cannon4";
            Cannon.base_stats[S.fertility] = 0.0f;
            Cannon.base_stats[S.max_children] = 0f;
            Cannon.base_stats[S.max_age] = 0f;
            Cannon.base_stats[S.attack_speed] = -30;
            Cannon.base_stats[S.damage] = 600;
            Cannon.base_stats[S.speed] = -18f;
            Cannon.base_stats[S.health] = 20;
            Cannon.setCost(1, "gold", 2);
            Cannon.base_stats[S.accuracy] = 60;
            Cannon.base_stats[S.range] = 25;
            Cannon.quality = ItemQuality.Legendary;
            Cannon.equipment_value = 89999;
            Cannon.tech_needed = "Siegeweapons";
            Cannon.equipmentType = EquipmentType.Weapon;
            Cannon.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Cannon);
            Localization.addLocalization("item_Cannon", "Cannon");
			addWeaponsSprite(Cannon.id, Cannon.materials[0]);
			
			
            ItemAsset Catapult = AssetManager.items.clone("Catapult", "_range");
            Catapult.id = "Catapult";
            Catapult.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Catapult.materials = new List<string> { "iron" };
            Catapult.projectile = "Catapult4";
            Catapult.base_stats[S.fertility] = 0.0f;
            Catapult.base_stats[S.max_children] = 0f;
            Catapult.base_stats[S.max_age] = 0f;
            Catapult.base_stats[S.attack_speed] = -25;
            Catapult.base_stats[S.damage] = 90;
            Catapult.base_stats[S.speed] = -5f;
            Catapult.base_stats[S.health] = 200;
            Catapult.setCost(1, "gold", 2);
            Catapult.base_stats[S.accuracy] = 50;
            Catapult.base_stats[S.range] = 10;
            Catapult.base_stats[S.armor] = 0;
            Catapult.base_stats[S.scale] = 0.0f;
            Catapult.base_stats[S.dodge] = 0f;
            Catapult.base_stats[S.targets] = 0f;
            Catapult.base_stats[S.critical_chance] = 0.0f;
            Catapult.base_stats[S.knockback] = 0f;
            Catapult.base_stats[S.knockback_reduction] = 0f;
            Catapult.base_stats[S.intelligence] = 0;
            Catapult.base_stats[S.warfare] = 0;
            Catapult.quality = ItemQuality.Legendary;
            Catapult.base_stats[S.diplomacy] = 0;
            Catapult.base_stats[S.stewardship] = 0;
            Catapult.base_stats[S.opinion] = 0f;
            Catapult.base_stats[S.loyalty_traits] = 0f;
            Catapult.base_stats[S.cities] = 0;
            Catapult.base_stats[S.zone_range] = 0;
            Catapult.equipment_value = 89999;
            Catapult.tech_needed = "Siegeweapons";
            Catapult.equipmentType = EquipmentType.Weapon;
            Catapult.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Catapult);
            Localization.addLocalization("item_Catapult", "Catapult");
			addWeaponsSprite(Catapult.id, Catapult.materials[0]);
			
            ItemAsset Ballista = AssetManager.items.clone("Ballista", "_range");
            Ballista.id = "Ballista";
            Ballista.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Ballista.materials = new List<string> { "iron" };
            Ballista.projectile = "Ballista4";
            Ballista.base_stats[S.fertility] = 0.0f;
            Ballista.base_stats[S.max_children] = 0f;
            Ballista.base_stats[S.max_age] = 0f;
            Ballista.base_stats[S.attack_speed] = -28;
            Ballista.base_stats[S.damage] = 1400;
            Ballista.base_stats[S.speed] = -12f;
            Ballista.base_stats[S.health] = 20;
            Ballista.setCost(1, "gold", 2);
            Ballista.base_stats[S.accuracy] = 90;
            Ballista.base_stats[S.range] = 15;
            Ballista.quality = ItemQuality.Legendary;
            Ballista.equipment_value = 89999;
            Ballista.tech_needed = "Siegeweapons";
            Ballista.equipmentType = EquipmentType.Weapon;
            Ballista.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Ballista);
            Localization.addLocalization("item_Ballista", "Ballista");
			addWeaponsSprite(Ballista.id, Ballista.materials[0]);
		  
		  
            ItemAsset H4TAtaque = AssetManager.items.clone("H4TAtaque", "_range");
            H4TAtaque.id = "H4TAtaque";
            H4TAtaque.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            H4TAtaque.materials = new List<string> { "iron" };
            H4TAtaque.projectile = "BalaH4T4";
            H4TAtaque.base_stats[S.fertility] = 0.0f;
            H4TAtaque.base_stats[S.max_children] = 0f;
            H4TAtaque.base_stats[S.max_age] = 0f;
            H4TAtaque.base_stats[S.attack_speed] = 10;
            H4TAtaque.base_stats[S.damage] = 10;
            H4TAtaque.base_stats[S.speed] = -20f;
            H4TAtaque.base_stats[S.health] = 200;
            H4TAtaque.setCost(1, "gold", 2);
            H4TAtaque.base_stats[S.accuracy] = -30;
            H4TAtaque.base_stats[S.range] = 10;
            H4TAtaque.base_stats[S.armor] = 0;
            H4TAtaque.base_stats[S.scale] = 0.0f;
            H4TAtaque.base_stats[S.dodge] = 0f;
            H4TAtaque.base_stats[S.targets] = 5f;
            H4TAtaque.base_stats[S.critical_chance] = 0.0f;
            H4TAtaque.base_stats[S.knockback] = 0f;
            H4TAtaque.base_stats[S.knockback_reduction] = 0f;
            H4TAtaque.base_stats[S.intelligence] = 0;
            H4TAtaque.base_stats[S.warfare] = 0;
            H4TAtaque.quality = ItemQuality.Legendary;
            H4TAtaque.base_stats[S.diplomacy] = 0;
            H4TAtaque.base_stats[S.stewardship] = 0;
            H4TAtaque.base_stats[S.opinion] = 0f;
            H4TAtaque.base_stats[S.loyalty_traits] = 0f;
            H4TAtaque.base_stats[S.cities] = 0;
            H4TAtaque.base_stats[S.zone_range] = 0;
            H4TAtaque.equipment_value = 89999;
            H4TAtaque.path_slash_animation = "effects/slashes/slash_shotgun";
            H4TAtaque.tech_needed = "Industria_HT's";
            H4TAtaque.equipmentType = EquipmentType.Weapon;
            H4TAtaque.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(H4TAtaque);
            Localization.addLocalization("item_H4TAtaque", "H4TAtaque");
			
			
            ItemAsset H5TAtaque = AssetManager.items.clone("H5TAtaque", "_range");
            H5TAtaque.id = "H5TAtaque";
            H5TAtaque.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            H5TAtaque.materials = new List<string> { "iron" };
            H5TAtaque.projectile = "BalaH5T4";
            H5TAtaque.base_stats[S.fertility] = 0.0f;
            H5TAtaque.base_stats[S.max_children] = 0f;
            H5TAtaque.base_stats[S.max_age] = 0f;
            H5TAtaque.base_stats[S.attack_speed] = 10;
            H5TAtaque.base_stats[S.damage] = 10;
            H5TAtaque.base_stats[S.speed] = -15f;
            H5TAtaque.base_stats[S.health] = 200;
            H5TAtaque.setCost(1, "gold", 6);
            H5TAtaque.base_stats[S.accuracy] = -30;
            H5TAtaque.base_stats[S.range] = 10;
            H5TAtaque.base_stats[S.armor] = 0;
            H5TAtaque.base_stats[S.scale] = 0.0f;
            H5TAtaque.base_stats[S.dodge] = 0f;
            H5TAtaque.base_stats[S.targets] = 5f;
            H5TAtaque.base_stats[S.critical_chance] = 0.0f;
            H5TAtaque.base_stats[S.knockback] = 0f;
            H5TAtaque.base_stats[S.knockback_reduction] = 0f;
            H5TAtaque.base_stats[S.intelligence] = 0;
            H5TAtaque.base_stats[S.warfare] = 0;
            H5TAtaque.quality = ItemQuality.Legendary;
            H5TAtaque.base_stats[S.diplomacy] = 0;
            H5TAtaque.base_stats[S.stewardship] = 0;
            H5TAtaque.base_stats[S.opinion] = 0f;
            H5TAtaque.base_stats[S.loyalty_traits] = 0f;
            H5TAtaque.base_stats[S.cities] = 0;
            H5TAtaque.base_stats[S.zone_range] = 0;
            H5TAtaque.equipment_value = 89999;
            H5TAtaque.path_slash_animation = "effects/slashes/slash_shotgun";
            H5TAtaque.tech_needed = "Industria_HT's";
            H5TAtaque.equipmentType = EquipmentType.Weapon;
            H5TAtaque.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(H5TAtaque);
            Localization.addLocalization("item_H5TAtaque", "H5TAtaque");
			
            ItemAsset OM01Ataque = AssetManager.items.clone("OM01Ataque", "_range");
            OM01Ataque.id = "OM01Ataque";
            OM01Ataque.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            OM01Ataque.materials = new List<string> { "iron" };
            OM01Ataque.projectile = "SlashOm11";
            OM01Ataque.base_stats[S.fertility] = 0.0f;
            OM01Ataque.base_stats[S.max_children] = 0f;
            OM01Ataque.base_stats[S.max_age] = 0f;
            OM01Ataque.base_stats[S.attack_speed] = 0;
            OM01Ataque.base_stats[S.damage] = 10;
            OM01Ataque.base_stats[S.speed] = 0f;
            OM01Ataque.base_stats[S.health] = 0;
            OM01Ataque.setCost(1, "gold", 6);
            OM01Ataque.base_stats[S.accuracy] = 0;
            OM01Ataque.base_stats[S.range] = 28;
            OM01Ataque.base_stats[S.armor] = 0;
            OM01Ataque.base_stats[S.scale] = 0.0f;
            OM01Ataque.base_stats[S.dodge] = 0f;
            OM01Ataque.base_stats[S.targets] = 0f;
            OM01Ataque.base_stats[S.critical_chance] = 0.0f;
            OM01Ataque.base_stats[S.knockback] = 0f;
            OM01Ataque.base_stats[S.knockback_reduction] = 0f;
            OM01Ataque.base_stats[S.intelligence] = 0;
            OM01Ataque.base_stats[S.warfare] = 0;
            OM01Ataque.quality = ItemQuality.Legendary;
            OM01Ataque.base_stats[S.diplomacy] = 0;
            OM01Ataque.base_stats[S.stewardship] = 0;
            OM01Ataque.base_stats[S.opinion] = 0f;
            OM01Ataque.base_stats[S.loyalty_traits] = 0f;
            OM01Ataque.base_stats[S.cities] = 0;
            OM01Ataque.base_stats[S.zone_range] = 0;
            OM01Ataque.equipment_value = 89999;
            OM01Ataque.path_slash_animation = "effects/slashes/slash_shotgun";
            OM01Ataque.tech_needed = "Industria_OM's";
            OM01Ataque.equipmentType = EquipmentType.Weapon;
            OM01Ataque.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(OM01Ataque);		
            Localization.addLocalization("item_OM01Ataque", "OM01Ataque");
			
            ItemAsset UL15Ataque = AssetManager.items.clone("UL15Ataque", "_range");
            UL15Ataque.id = "UL15Ataque";
            UL15Ataque.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            UL15Ataque.materials = new List<string> { "iron" };
            UL15Ataque.projectile = "UltraProyectile4";
            UL15Ataque.base_stats[S.fertility] = 0.0f;
            UL15Ataque.base_stats[S.max_children] = 0f;
            UL15Ataque.base_stats[S.max_age] = 0f;
            UL15Ataque.base_stats[S.attack_speed] = 0;
            UL15Ataque.base_stats[S.damage] = 100;
            UL15Ataque.base_stats[S.speed] = 0f;
            UL15Ataque.base_stats[S.health] = 0;
            UL15Ataque.setCost(1, "gold", 6);
            UL15Ataque.base_stats[S.accuracy] = 0;
            UL15Ataque.base_stats[S.range] = 60;
            UL15Ataque.base_stats[S.armor] = 0;
            UL15Ataque.base_stats[S.scale] = 0.0f;
            UL15Ataque.base_stats[S.dodge] = 0f;
            UL15Ataque.base_stats[S.targets] = 3f;
            UL15Ataque.base_stats[S.critical_chance] = 0.0f;
            UL15Ataque.base_stats[S.knockback] = 0f;
            UL15Ataque.base_stats[S.knockback_reduction] = 0f;
            UL15Ataque.base_stats[S.intelligence] = 0;
            UL15Ataque.base_stats[S.warfare] = 0;
            UL15Ataque.quality = ItemQuality.Legendary;
            UL15Ataque.base_stats[S.diplomacy] = 0;
            UL15Ataque.base_stats[S.stewardship] = 0;
            UL15Ataque.base_stats[S.opinion] = 0f;
            UL15Ataque.base_stats[S.loyalty_traits] = 0f;
            UL15Ataque.base_stats[S.cities] = 0;
            UL15Ataque.base_stats[S.zone_range] = 0;
            UL15Ataque.equipment_value = 89999;
            UL15Ataque.path_slash_animation = "effects/slashes/slash_shotgun";
            UL15Ataque.tech_needed = "Industria_OM's";
            UL15Ataque.equipmentType = EquipmentType.Weapon;
            UL15Ataque.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(UL15Ataque);		
            Localization.addLocalization("item_UL15Ataque", "UL15Ataque");
			
			ItemAsset katana = AssetManager.items.clone("katana", "sword");
            katana.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            katana.materials = new List<string> { "iron" };
            katana.equipmentType = EquipmentType.Weapon;
            katana.quality = ItemQuality.Rare;
            katana.name_class = "item_class_weapon";
			katana.tech_needed = "WeaponsPlus";
            katana.base_stats[S.attack_speed] = 75f;
            katana.base_stats[S.targets] = 1;
            katana.base_stats[S.damage] = 160;
            katana.base_stats[S.health] = 0;
            katana.base_stats[S.critical_chance] = 0.3f;
            katana.base_stats[S.critical_damage_multiplier] = 1f;
            katana.equipment_value = 80;
            katana.setCost(1, "iron", 1, "gold", 1);
            AssetManager.items.list.AddItem(katana);
            Localization.addLocalization("item_katana", "katana");
			addWeaponsSprite(katana.id, katana.materials[0]);

            ItemAsset knife = AssetManager.items.clone("knife", "sword");
            knife.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            knife.materials = new List<string> { "iron" };
            knife.equipmentType = EquipmentType.Weapon;
            knife.quality = ItemQuality.Rare;
            knife.name_class = "item_class_weapon";
			knife.tech_needed = "WeaponsPlus";
            knife.base_stats[S.attack_speed] = 85f;
            knife.base_stats[S.targets] = 1;
            knife.base_stats[S.damage] = 30;
            knife.base_stats[S.health] = 0;
            knife.base_stats[S.critical_chance] = 0.3f;
            knife.base_stats[S.critical_damage_multiplier] = 1f;
            knife.equipment_value = 80;
            knife.setCost(1, "iron", 1);
            AssetManager.items.list.AddItem(knife);
            Localization.addLocalization("item_knife", "knife");
			addWeaponsSprite(knife.id, knife.materials[0]);	

            ItemAsset war_axe = AssetManager.items.clone("war_axe", "axe");
            war_axe.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            war_axe.materials = new List<string> { "iron" };
            war_axe.equipmentType = EquipmentType.Weapon;
            war_axe.quality = ItemQuality.Rare;
            war_axe.name_class = "item_class_weapon";
			war_axe.tech_needed = "WeaponsPlus";
            war_axe.base_stats[S.attack_speed] = -10f;
            war_axe.base_stats[S.targets] = 1;
            war_axe.base_stats[S.damage] = 90;
            war_axe.base_stats[S.health] = 0;
            war_axe.base_stats[S.critical_chance] = 0.5f;
            war_axe.base_stats[S.critical_damage_multiplier] = 2f;
            war_axe.equipment_value = 80;
            war_axe.setCost(1, "iron", 1);
            AssetManager.items.list.AddItem(war_axe);
            Localization.addLocalization("item_war_axe", "War Axe");
			addWeaponsSprite(war_axe.id, war_axe.materials[0]);				

            ItemAsset Large_war_axe = AssetManager.items.clone("Large_war_axe", "axe");
            Large_war_axe.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Large_war_axe.materials = new List<string> { "iron" };
            Large_war_axe.equipmentType = EquipmentType.Weapon;
            Large_war_axe.quality = ItemQuality.Rare;
            Large_war_axe.name_class = "item_class_weapon";
			Large_war_axe.tech_needed = "WeaponsPlus";
            Large_war_axe.base_stats[S.attack_speed] = -13f;
			Large_war_axe.base_stats[S.speed] = -24f;
			Large_war_axe.base_stats[S.range] = 0.2f;
            Large_war_axe.base_stats[S.targets] = 1;
            Large_war_axe.base_stats[S.damage] = 140;
            Large_war_axe.base_stats[S.health] = 0;
            Large_war_axe.base_stats[S.critical_chance] = 0.5f;
            Large_war_axe.base_stats[S.critical_damage_multiplier] = 2f;
            Large_war_axe.equipment_value = 80;
            Large_war_axe.setCost(1, "iron", 1);
            AssetManager.items.list.AddItem(Large_war_axe);
            Localization.addLocalization("item_Large_war_axe", "Large War Axe");
			addWeaponsSprite(Large_war_axe.id, Large_war_axe.materials[0]);		

			ItemAsset Advanced_sword = AssetManager.items.clone("Advanced_sword", "sword");
            Advanced_sword.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Advanced_sword.materials = List.Of<string>(new string[]
		 {
			"mythril"
		 });
            Advanced_sword.equipmentType = EquipmentType.Weapon;
            Advanced_sword.quality = ItemQuality.Rare;
            Advanced_sword.name_class = "item_class_weapon";
			Advanced_sword.tech_needed = "WeaponsPlus";
            Advanced_sword.base_stats[S.attack_speed] = 45f;
            Advanced_sword.base_stats[S.targets] = 1;
            Advanced_sword.base_stats[S.damage] = 120;
            Advanced_sword.base_stats[S.health] = 20;
            Advanced_sword.base_stats[S.critical_chance] = 0.2f;
            Advanced_sword.base_stats[S.critical_damage_multiplier] = 1f;
            Advanced_sword.equipment_value = 80;
            Advanced_sword.setCost(1, "iron", 1, "mythril", 1);
            AssetManager.items.list.AddItem(Advanced_sword);
            Localization.addLocalization("item_Advanced_sword", "Advanced sword");
			addWeaponsSprite(Advanced_sword.id, Advanced_sword.materials[0]);

			ItemAsset Large_sword = AssetManager.items.clone("Large_sword", "sword");
            Large_sword.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Large_sword.materials = List.Of<string>(new string[]
		 {
			"wood"
		 });
            Large_sword.equipmentType = EquipmentType.Weapon;
            Large_sword.quality = ItemQuality.Rare;
            Large_sword.name_class = "item_class_weapon";
			Large_sword.tech_needed = "WeaponsPlus";
            Large_sword.base_stats[S.attack_speed] = 45f;
            Large_sword.base_stats[S.targets] = 1;
			Large_sword.base_stats[S.range] = 0.2f;
            Large_sword.base_stats[S.damage] = 120;
            Large_sword.base_stats[S.health] = 20;
            Large_sword.base_stats[S.critical_chance] = 0.2f;
            Large_sword.base_stats[S.critical_damage_multiplier] = 1f;
            Large_sword.equipment_value = 80;
            Large_sword.setCost(1, "wood", 1);
            AssetManager.items.list.AddItem(Large_sword);
            Localization.addLocalization("item_Large_sword", "Large sword");
			addWeaponsSprite(Large_sword.id, Large_sword.materials[0]);	


            ItemAsset Arcabuz = AssetManager.items.clone("Arcabuz", "_range");
            Arcabuz.id = "Arcabuz";
            Arcabuz.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Arcabuz.materials = new List<string> { "iron" };
            Arcabuz.projectile = "Bala";
            Arcabuz.base_stats[S.attack_speed] = 40;
            Arcabuz.base_stats[S.damage] = 90;
            Arcabuz.setCost(1, "iron", 1);
            Arcabuz.base_stats[S.accuracy] = 60;
            Arcabuz.base_stats[S.range] = 15;
            Arcabuz.base_stats[S.armor] = 0;
            Arcabuz.base_stats[S.scale] = 0.0f;
            Arcabuz.base_stats[S.dodge] = 0f;
            Arcabuz.base_stats[S.targets] = 0f;
            Arcabuz.base_stats[S.critical_chance] = 0.0f;
            Arcabuz.base_stats[S.knockback] = 0.2f;
            Arcabuz.base_stats[S.knockback_reduction] = 0f;
            Arcabuz.quality = ItemQuality.Legendary;
            Arcabuz.equipment_value = 89999;
            Arcabuz.tech_needed = "OldGuns";
            Arcabuz.equipmentType = EquipmentType.Weapon;
            Arcabuz.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Arcabuz);
            Localization.addLocalization("item_Arcabuz", "Arcabuz");
			addWeaponsSprite(Arcabuz.id, Arcabuz.materials[0]);	

            ItemAsset Mosquete = AssetManager.items.clone("Mosquete", "_range");
            Mosquete.id = "Mosquete";
            Mosquete.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Mosquete.materials = new List<string> { "iron" };
            Mosquete.projectile = "Bala";
            Mosquete.base_stats[S.attack_speed] = -40;
            Mosquete.base_stats[S.damage] = 150;
            Mosquete.setCost(1, "iron", 1);
            Mosquete.base_stats[S.accuracy] = 80;
			Mosquete.base_stats[S.speed] = -15f;
            Mosquete.base_stats[S.range] = 25;
            Mosquete.base_stats[S.armor] = 0;
            Mosquete.base_stats[S.knockback] = 0.3f;
            Mosquete.quality = ItemQuality.Legendary;
            Mosquete.equipment_value = 89999;
            Mosquete.tech_needed = "OldGuns";
            Mosquete.equipmentType = EquipmentType.Weapon;
            Mosquete.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Mosquete);
            Localization.addLocalization("item_Mosquete", "Mosquete");
			addWeaponsSprite(Mosquete.id, Mosquete.materials[0]);	

            ItemAsset PistolaDeChispa = AssetManager.items.clone("PistolaDeChispa", "_range");
            PistolaDeChispa.id = "PistolaDeChispa";
            PistolaDeChispa.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            PistolaDeChispa.materials = new List<string> { "iron" };
            PistolaDeChispa.projectile = "Bala";
            PistolaDeChispa.base_stats[S.attack_speed] = -50;
            PistolaDeChispa.base_stats[S.damage] = 140;
            PistolaDeChispa.setCost(1, "iron", 1);
            PistolaDeChispa.base_stats[S.accuracy] = 50;
			PistolaDeChispa.base_stats[S.speed] = 0f;
            PistolaDeChispa.base_stats[S.range] = 15;
            PistolaDeChispa.base_stats[S.armor] = 0;
            PistolaDeChispa.base_stats[S.knockback] = 0.5f;
            PistolaDeChispa.quality = ItemQuality.Legendary;
            PistolaDeChispa.equipment_value = 89999;
            PistolaDeChispa.tech_needed = "OldGuns";
            PistolaDeChispa.equipmentType = EquipmentType.Weapon;
            PistolaDeChispa.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(PistolaDeChispa);
            Localization.addLocalization("item_PistolaDeChispa", "PistolaDeChispa");
			addWeaponsSprite(PistolaDeChispa.id, PistolaDeChispa.materials[0]);	

            ItemAsset Falconete = AssetManager.items.clone("Falconete", "_range");
            Falconete.id = "Falconete";
            Falconete.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Falconete.materials = new List<string> { "iron" };
            Falconete.projectile = "Bala";
            Falconete.base_stats[S.attack_speed] = 140;
            Falconete.base_stats[S.damage] = 50;
            Falconete.setCost(1, "iron", 1);
            Falconete.base_stats[S.accuracy] = 60;
			Falconete.base_stats[S.speed] = 0f;
            Falconete.base_stats[S.range] = 15;
            Falconete.base_stats[S.armor] = 10;
            Falconete.base_stats[S.knockback] = 0.0f;
            Falconete.quality = ItemQuality.Legendary;
            Falconete.equipment_value = 89999;
            Falconete.tech_needed = "OldGuns";
            Falconete.equipmentType = EquipmentType.Weapon;
            Falconete.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Falconete);
            Localization.addLocalization("item_Falconete", "Falconete");
			addWeaponsSprite(Falconete.id, Falconete.materials[0]);		

            ItemAsset Culebrina = AssetManager.items.clone("Culebrina", "_range");
            Culebrina.id = "Culebrina";
            Culebrina.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Culebrina.materials = new List<string> { "iron" };
            Culebrina.projectile = "Cannon4";
            Culebrina.base_stats[S.attack_speed] = -60;
            Culebrina.base_stats[S.damage] = 490;
            Culebrina.setCost(1, "iron", 15);
            Culebrina.base_stats[S.accuracy] = 80;
            Culebrina.base_stats[S.range] = 20;
            Culebrina.base_stats[S.armor] = 60;
            Culebrina.base_stats[S.knockback] = 0.2f;
            Culebrina.quality = ItemQuality.Legendary;
            Culebrina.equipment_value = 89999;
            Culebrina.tech_needed = "OldGuns";
            Culebrina.equipmentType = EquipmentType.Weapon;
            Culebrina.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Culebrina);
            Localization.addLocalization("item_Culebrina", "Culebrina");
			addWeaponsSprite(Culebrina.id, Culebrina.materials[0]);	

            ItemAsset AK_47 = AssetManager.items.clone("AK_47", "_range");
            AK_47.id = "AK_47";
            AK_47.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            AK_47.materials = new List<string> { "iron" };
            AK_47.projectile = "Bala12";
            AK_47.base_stats[S.attack_speed] = 160;
            AK_47.base_stats[S.damage] = 90;
            AK_47.setCost(1, "iron", 2);
            AK_47.base_stats[S.accuracy] = 60;
            AK_47.base_stats[S.range] = 16;
            AK_47.base_stats[S.targets] = 0f;
            AK_47.base_stats[S.critical_chance] = 0.0f;
            AK_47.base_stats[S.knockback_reduction] = 0f;
            AK_47.quality = ItemQuality.Legendary;
            AK_47.equipment_value = 89999;
            AK_47.tech_needed = "ModernGuns";
            AK_47.equipmentType = EquipmentType.Weapon;
            AK_47.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(AK_47);
            Localization.addLocalization("item_AK_47", "AK_47");
			addWeaponsSprite(AK_47.id, AK_47.materials[0]);	

            ItemAsset M16A1 = AssetManager.items.clone("M16A1", "_range");
            M16A1.id = "M16A1";
            M16A1.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            M16A1.materials = new List<string> { "iron" };
            M16A1.projectile = "Bala12";
            M16A1.base_stats[S.attack_speed] = 190;
            M16A1.base_stats[S.damage] = 80;
            M16A1.setCost(1, "iron", 2);
            M16A1.base_stats[S.accuracy] = 60;
            M16A1.base_stats[S.range] = 16;
            M16A1.base_stats[S.targets] = 0f;
            M16A1.base_stats[S.critical_chance] = 0.0f;
            M16A1.base_stats[S.knockback_reduction] = 0f;
            M16A1.quality = ItemQuality.Legendary;
            M16A1.equipment_value = 89999;
            M16A1.tech_needed = "ModernGuns";
            M16A1.equipmentType = EquipmentType.Weapon;
            M16A1.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(M16A1);
            Localization.addLocalization("item_M16A1", "M16A1");
			addWeaponsSprite(M16A1.id, M16A1.materials[0]);		

            ItemAsset Glock_17 = AssetManager.items.clone("Glock_17", "_range");
            Glock_17.id = "Glock_17";
            Glock_17.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Glock_17.materials = new List<string> { "iron" };
            Glock_17.projectile = "Bala12";
            Glock_17.base_stats[S.attack_speed] = 40;
            Glock_17.base_stats[S.damage] = 50;
            Glock_17.setCost(1, "iron", 1);
            Glock_17.base_stats[S.accuracy] = 60;
            Glock_17.base_stats[S.range] = 16;
            Glock_17.base_stats[S.targets] = 0f;
            Glock_17.base_stats[S.critical_chance] = 0.2f;
            Glock_17.base_stats[S.knockback_reduction] = 0f;
            Glock_17.quality = ItemQuality.Legendary;
            Glock_17.equipment_value = 89999;
            Glock_17.tech_needed = "ModernGuns";
            Glock_17.equipmentType = EquipmentType.Weapon;
            Glock_17.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(Glock_17);
            Localization.addLocalization("item_Glock_17", "Glock_17");
			addWeaponsSprite(Glock_17.id, Glock_17.materials[0]);		

            ItemAsset BarrettM82 = AssetManager.items.clone("BarrettM82", "_range");
            BarrettM82.id = "BarrettM82";
            BarrettM82.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            BarrettM82.materials = new List<string> { "iron" };
            BarrettM82.projectile = "Bala12";
            BarrettM82.base_stats[S.attack_speed] = -80;
            BarrettM82.base_stats[S.damage] = 500;
            BarrettM82.setCost(1, "iron", 4);
            BarrettM82.base_stats[S.accuracy] = 90;
            BarrettM82.base_stats[S.range] = 51;
            BarrettM82.base_stats[S.targets] = 0f;
            BarrettM82.base_stats[S.critical_chance] = 0.2f;
            BarrettM82.base_stats[S.knockback_reduction] = 0f;
            BarrettM82.quality = ItemQuality.Legendary;
            BarrettM82.equipment_value = 89999;
            BarrettM82.tech_needed = "ModernGuns";
            BarrettM82.equipmentType = EquipmentType.Weapon;
            BarrettM82.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(BarrettM82);
            Localization.addLocalization("item_BarrettM82", "BarrettM82");
			addWeaponsSprite(BarrettM82.id, BarrettM82.materials[0]);	

            ItemAsset UziP = AssetManager.items.clone("UziP", "_range");
            UziP.id = "UziP";
            UziP.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            UziP.materials = new List<string> { "iron" };
            UziP.projectile = "Bala12";
            UziP.base_stats[S.attack_speed] = 160;
            UziP.base_stats[S.damage] = 5;
            UziP.setCost(1, "iron", 2);
            UziP.base_stats[S.accuracy] = 30;
            UziP.base_stats[S.range] = 25;
            UziP.base_stats[S.targets] = 0f;
            UziP.base_stats[S.critical_chance] = 0.2f;
            UziP.base_stats[S.knockback_reduction] = 0f;
            UziP.quality = ItemQuality.Legendary;
            UziP.equipment_value = 89999;
            UziP.tech_needed = "ModernGuns";
            UziP.equipmentType = EquipmentType.Weapon;
            UziP.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(UziP);
            Localization.addLocalization("item_UziP", "UziP");
			addWeaponsSprite(UziP.id, UziP.materials[0]);		

            ItemAsset BenelliM4 = AssetManager.items.clone("BenelliM4", "_range");
            BenelliM4.id = "BenelliM4";
            BenelliM4.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            BenelliM4.materials = new List<string> { "iron" };
            BenelliM4.projectile = "shotgun_bullet";
            BenelliM4.base_stats[S.attack_speed] = 40;
            BenelliM4.base_stats[S.damage] = 70;
            BenelliM4.setCost(1, "iron", 2);
            BenelliM4.base_stats[S.accuracy] = 60;
            BenelliM4.base_stats[S.range] = 25;
            BenelliM4.base_stats[S.targets] = 0f;
            BenelliM4.base_stats[S.critical_chance] = 0.2f;
            BenelliM4.base_stats[S.knockback_reduction] = 0f;
            BenelliM4.quality = ItemQuality.Legendary;
            BenelliM4.equipment_value = 89999;
            BenelliM4.tech_needed = "ModernGuns";
            BenelliM4.equipmentType = EquipmentType.Weapon;
            BenelliM4.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(BenelliM4);
            Localization.addLocalization("item_BenelliM4", "BenelliM4");
			addWeaponsSprite(BenelliM4.id, BenelliM4.materials[0]);		

            ItemAsset PlasmaCutter5000 = AssetManager.items.clone("PlasmaCutter5000", "_range");
            PlasmaCutter5000.id = "PlasmaCutter5000";
            PlasmaCutter5000.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            PlasmaCutter5000.materials = new List<string> { "technotite" };
            PlasmaCutter5000.projectile = "BlueLaser4";
            PlasmaCutter5000.base_stats[S.attack_speed] = 40;
            PlasmaCutter5000.base_stats[S.damage] = 120;
            PlasmaCutter5000.setCost(1, "technotite", 1);
            PlasmaCutter5000.base_stats[S.accuracy] = 60;
            PlasmaCutter5000.base_stats[S.range] = 40;
            PlasmaCutter5000.base_stats[S.targets] = 0f;
            PlasmaCutter5000.base_stats[S.critical_chance] = 0.3f;
            PlasmaCutter5000.base_stats[S.knockback_reduction] = 0f;
            PlasmaCutter5000.quality = ItemQuality.Legendary;
            PlasmaCutter5000.equipment_value = 89999;
            PlasmaCutter5000.tech_needed = "FuturisticGuns";
            PlasmaCutter5000.equipmentType = EquipmentType.Weapon;
            PlasmaCutter5000.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(PlasmaCutter5000);
            Localization.addLocalization("item_PlasmaCutter5000", "PlasmaCutter5000");
			addWeaponsSprite(PlasmaCutter5000.id, PlasmaCutter5000.materials[0]);		

            ItemAsset RailgunX900 = AssetManager.items.clone("RailgunX900", "_range");
            RailgunX900.id = "RailgunX900";
            RailgunX900.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            RailgunX900.materials = new List<string> { "technotite" };
            RailgunX900.projectile = "BallLaserBlue4";
            RailgunX900.base_stats[S.attack_speed] = 60;
            RailgunX900.base_stats[S.damage] = 190;
            RailgunX900.setCost(1, "technotite", 1);
            RailgunX900.base_stats[S.accuracy] = 60;
            RailgunX900.base_stats[S.range] = 47;
            RailgunX900.base_stats[S.targets] = 0f;
            RailgunX900.base_stats[S.critical_chance] = 0.5f;
            RailgunX900.base_stats[S.knockback_reduction] = 0f;
			RailgunX900.base_stats[S.knockback] = 0.5f;
            RailgunX900.quality = ItemQuality.Legendary;
            RailgunX900.equipment_value = 89999;
            RailgunX900.tech_needed = "FuturisticGuns";
            RailgunX900.equipmentType = EquipmentType.Weapon;
            RailgunX900.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(RailgunX900);
            Localization.addLocalization("item_RailgunX900", "RailgunX900");
			addWeaponsSprite(RailgunX900.id, RailgunX900.materials[0]);	

            ItemAsset FusionBlasterMk = AssetManager.items.clone("FusionBlasterMk", "_range");
            FusionBlasterMk.id = "FusionBlasterMk";
            FusionBlasterMk.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            FusionBlasterMk.materials = new List<string> { "technotite" };
            FusionBlasterMk.projectile = "LaserBlueSmall4";
            FusionBlasterMk.base_stats[S.attack_speed] = 70;
            FusionBlasterMk.base_stats[S.damage] = 200;
            FusionBlasterMk.setCost(1, "technotite", 1);
            FusionBlasterMk.base_stats[S.accuracy] = 90;
			FusionBlasterMk.action_attack_target = new AttackAction(FusionBlasterMkPower);
            FusionBlasterMk.base_stats[S.range] = 54;
            FusionBlasterMk.base_stats[S.critical_chance] = 0.2f;
            FusionBlasterMk.base_stats[S.knockback] = 0.734f;
            FusionBlasterMk.quality = ItemQuality.Legendary;
            FusionBlasterMk.equipment_value = 89999;
            FusionBlasterMk.tech_needed = "FuturisticGuns";
            FusionBlasterMk.equipmentType = EquipmentType.Weapon;
            FusionBlasterMk.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(FusionBlasterMk);
            Localization.addLocalization("item_FusionBlasterMk", "FusionBlasterMk");
			addWeaponsSprite(FusionBlasterMk.id, FusionBlasterMk.materials[0]);	

            ItemAsset NaniteSwarmLauncher = AssetManager.items.clone("NaniteSwarmLauncher", "_range");
            NaniteSwarmLauncher.id = "NaniteSwarmLauncher";
            NaniteSwarmLauncher.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            NaniteSwarmLauncher.materials = new List<string> { "technotite" };
            NaniteSwarmLauncher.projectile = "BlueLaser4";
            NaniteSwarmLauncher.base_stats[S.attack_speed] = 40;
            NaniteSwarmLauncher.base_stats[S.damage] = 280;
            NaniteSwarmLauncher.setCost(1, "technotite", 1);
            NaniteSwarmLauncher.base_stats[S.accuracy] = 90;
            NaniteSwarmLauncher.base_stats[S.range] = 50;
            NaniteSwarmLauncher.base_stats[S.critical_chance] = 0.7f;
            NaniteSwarmLauncher.base_stats[S.knockback] = 0.734f;
            NaniteSwarmLauncher.quality = ItemQuality.Legendary;
            NaniteSwarmLauncher.equipment_value = 89999;
            NaniteSwarmLauncher.tech_needed = "FuturisticGuns";
            NaniteSwarmLauncher.equipmentType = EquipmentType.Weapon;
            NaniteSwarmLauncher.name_class = "item_class_weapon";
            AssetManager.items.list.AddItem(NaniteSwarmLauncher);
            Localization.addLocalization("item_NaniteSwarmLauncher", "NaniteSwarmLauncher");
			addWeaponsSprite(NaniteSwarmLauncher.id, NaniteSwarmLauncher.materials[0]);	

            ItemAsset PhotonRifleXR = AssetManager.items.clone("PhotonRifleXR", "_range");
            PhotonRifleXR.id = "PhotonRifleXR";
            PhotonRifleXR.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            PhotonRifleXR.materials = new List<string> { "technotite" };
            PhotonRifleXR.projectile = "SharpLaser54";
            PhotonRifleXR.base_stats[S.attack_speed] = 40;
            PhotonRifleXR.base_stats[S.damage] = 200;
            PhotonRifleXR.setCost(1, "iron", 1);
            PhotonRifleXR.base_stats[S.accuracy] = 120;
            PhotonRifleXR.base_stats[S.range] = 50;
            PhotonRifleXR.base_stats[S.critical_chance] = 0.7f;
            PhotonRifleXR.base_stats[S.knockback_reduction] = 1f;
            PhotonRifleXR.quality = ItemQuality.Legendary;
            PhotonRifleXR.equipment_value = 89999;
            PhotonRifleXR.tech_needed = "FuturisticGuns";
            PhotonRifleXR.equipmentType = EquipmentType.Weapon;
            PhotonRifleXR.name_class = "item_class_weapon";
			PhotonRifleXR.action_attack_target = new AttackAction(PhotonRifleXRPower);
            AssetManager.items.list.AddItem(PhotonRifleXR);
            Localization.addLocalization("item_PhotonRifleXR", "PhotonRifleXR");
			addWeaponsSprite(PhotonRifleXR.id, PhotonRifleXR.materials[0]);	

            ItemAsset Astra = AssetManager.items.clone("Astra", "_range"); 
            Astra.id = "Astra";
            Astra.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            Astra.materials = new List<string> { "technotite" };
            Astra.projectile = "BlueLaser4";
            Astra.base_stats[S.attack_speed] = 160;
            Astra.base_stats[S.damage] = 200;
            Astra.setCost(1, "technotite", 1);
            Astra.base_stats[S.accuracy] = 90;
            Astra.base_stats[S.range] = 64;
            Astra.base_stats[S.targets] = 0f;
            Astra.base_stats[S.critical_chance] = 0.3f;
            Astra.base_stats[S.knockback_reduction] = 0f;
			Astra.base_stats[S.knockback] = 0.60f;
            Astra.quality = ItemQuality.Legendary;
            Astra.equipment_value = 89999;
            Astra.tech_needed = "FuturisticGuns";
            Astra.equipmentType = EquipmentType.Weapon;
            Astra.name_class = "item_class_weapon";
			Astra.action_attack_target = new AttackAction(AstraPower);
            AssetManager.items.list.AddItem(Astra);
            Localization.addLocalization("item_Astra", "Astra");
			addWeaponsSprite(Astra.id, Astra.materials[0]);			

            ItemAsset ChaosX10 = AssetManager.items.clone("ChaosX10", "_range"); 
            ChaosX10.id = "ChaosX10";
            ChaosX10.name_templates = Toolbox.splitStringIntoList("sword_name#30", "sword_name_king#3", "weapon_name_city", "weapon_name_kingdom", "weapon_name_culture", "weapon_name_enemy_king", "weapon_name_enemy_kingdom");
            ChaosX10.materials = new List<string> { "technotite" };
            ChaosX10.projectile = "BlueLaser4";
            ChaosX10.base_stats[S.attack_speed] = 160;
            ChaosX10.base_stats[S.damage] = 200;
            ChaosX10.setCost(1, "technotite", 1);
            ChaosX10.base_stats[S.accuracy] = 90;
            ChaosX10.base_stats[S.range] = 64;
            ChaosX10.base_stats[S.targets] = 0f;
            ChaosX10.base_stats[S.critical_chance] = 0.3f;
            ChaosX10.base_stats[S.knockback_reduction] = 0f;
			ChaosX10.base_stats[S.knockback] = 0.60f;
            ChaosX10.quality = ItemQuality.Legendary;
            ChaosX10.equipment_value = 89999;
            ChaosX10.tech_needed = "FuturisticGuns";
            ChaosX10.equipmentType = EquipmentType.Weapon;
            ChaosX10.name_class = "item_class_weapon";
			ChaosX10.action_attack_target = new AttackAction(FusionBlasterMkPower);
            AssetManager.items.list.AddItem(ChaosX10);
            Localization.addLocalization("item_ChaosX10", "ChaosX10");
			addWeaponsSprite(ChaosX10.id, ChaosX10.materials[0]);					
			
 
        }
                
        public static bool AstraPower(BaseSimObject pSelf, BaseSimObject pTarget, WorldTile pTile = null)
        {
        if(pTarget != null){
        Actor a = Reflection.GetField(pTarget.GetType(), pTarget, "a") as Actor;
        if(Toolbox.randomChance(100.0f)){
         pTarget.CallMethod("addStatusEffect", "frozen", 20f);
		 pTarget.CallMethod("addStatusEffect", "DebilidadCriticaE", 20f);
          
          
          
        }
        }return false;

        }
        public static bool PhotonRifleXRPower(BaseSimObject pSelf, BaseSimObject pTarget, WorldTile pTile = null)
        {
            if (pTarget?.a is Actor a && Toolbox.randomChance(100.0f))
            {
                a.killHimself(false, AttackType.Tumor, false, true);
                return true;
            }
            return false;
        }
		public static bool FusionBlasterMkPower(BaseSimObject pSelf, BaseSimObject pTarget, WorldTile pTile = null)
		{
 		   if (pTarget != null)
 		   {
    		    Actor a = Reflection.GetField(pTarget.GetType(), pTarget, "a") as Actor;
   		     if (Toolbox.randomChance(100.0f))
   		     {
   		         pTarget.CallMethod("addStatusEffect", "FuegoAzul", 30f);
   		         return true;
    		    }
   		 }
  		  return false;
		}
            static void addWeaponsSprite(string id, string material)
            {
              var dictItems = Reflection.GetField(typeof(ActorAnimationLoader), null, "dictItems") as Dictionary<string, Sprite>;
              var sprite = Resources.Load<Sprite>("Weapons/w_" + id + "_" + material);
              dictItems.Add(sprite.name, sprite);
            }
        }
    }

