using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using ReflectionUtility;
using HarmonyLib;
using System.Reflection;
 
namespace AmbientWar
{
    class UnitsSiege
    {
        public static void init()
        {
			
         var Trabuchet = AssetManager.actor_library.clone("Trabuchet", "_mob");
         Trabuchet.race = "human";
         Trabuchet.kingdom = "human";
         Trabuchet.base_stats[S.attack_speed] = -20f;
         Trabuchet.base_stats[S.accuracy] = 100f;
         Trabuchet.base_stats[S.health] = 700;
		 Trabuchet.base_stats[S.scale] = 0.18f;
         Trabuchet.base_stats[S.speed] = 5f;
		 Trabuchet.base_stats[S.range] = 25;
         Trabuchet.base_stats[S.damage] = 500;
		 Trabuchet.base_stats[S.fertility] = -1.0f;
         Trabuchet.base_stats[S.knockback_reduction] = 1.0f;
         Trabuchet.base_stats[S.armor] = 50;
         Trabuchet.drawBoatMark_big = true;
         Trabuchet.skipFightLogic = false;
         Trabuchet.inspect_stats = true;
         Trabuchet.landCreature = true;
         Trabuchet.inspect_home = true;
         Trabuchet.drawBoatMark = true;
         Trabuchet.flying = false;
         Trabuchet.needFood = false;
         Trabuchet.can_edit_traits = false;
         Trabuchet.canReceiveTraits = false;
         Trabuchet.very_high_flyer = false;
         Trabuchet.isBoat = false;
         Trabuchet.moveFromBlock = false;
         Trabuchet.inspect_children = false;
         Trabuchet.inspect_experience = true;
         Trabuchet.disableJumpAnimation = true;
         Trabuchet.canBeCitizen = true;
         Trabuchet.inspect_kills = true;
		 Trabuchet.damagedByOcean = true;
         Trabuchet.use_items = false;
         Trabuchet.oceanCreature = false;
         Trabuchet.take_items = false;
         Trabuchet.tech = "Siegeweapons";
         Trabuchet.defaultAttack = "TrabuchetAtt";
         Trabuchet.nameLocale = "Trabuchet"; 
         Trabuchet.nameTemplate = "Asedio_Names";
         Trabuchet.job = "attacker";
         Trabuchet.icon = "iconTrabuchet";
         AssetManager.actor_library.CallMethod("loadShadow", Trabuchet);
         Trabuchet.animation_idle = "idle_0";
         Trabuchet.animation_walk = "walk_0,walk_1,walk_2,walk_2";
         Trabuchet.animation_swim = "swim_0,swim_1";
         Trabuchet.actorSize = ActorSize.S17_Dragon;
         Trabuchet.texture_path = "Trabuchet";
         AssetManager.actor_library.addColorSet("FFFColor");
         Localization.addLocalization(Trabuchet.nameLocale, Trabuchet.nameLocale);
         AssetManager.actor_library.add(Trabuchet);
		 AssetManager.actor_library.CallMethod("addTrait", "immortal");
         Trabuchet.color = Toolbox.makeColor("#33724D");
		 
         var Combat_wagon_big = AssetManager.actor_library.clone("Combat_wagon_big", "_mob");
         Combat_wagon_big.race = "human";
         Combat_wagon_big.kingdom = "human";
         Combat_wagon_big.base_stats[S.attack_speed] = 240f;
         Combat_wagon_big.base_stats[S.accuracy] = 80f;
         Combat_wagon_big.base_stats[S.health] = 430;
		 Combat_wagon_big.base_stats[S.scale] = 0.23f;
         Combat_wagon_big.base_stats[S.speed] = 15f;
		 Combat_wagon_big.base_stats[S.range] = 10;
         Combat_wagon_big.base_stats[S.damage] = 67;
		 Combat_wagon_big.base_stats[S.fertility] = -1.0f;
         Combat_wagon_big.base_stats[S.knockback_reduction] = 1.0f;
         Combat_wagon_big.base_stats[S.armor] = 40;
         Combat_wagon_big.skipFightLogic = false;
         Combat_wagon_big.inspect_stats = true;
         Combat_wagon_big.landCreature = true;
         Combat_wagon_big.inspect_home = true;
         Combat_wagon_big.drawBoatMark = true;
         Combat_wagon_big.flying = false;
         Combat_wagon_big.needFood = false;
         Combat_wagon_big.can_edit_traits = false;
         Combat_wagon_big.canReceiveTraits = false;
         Combat_wagon_big.very_high_flyer = false;
         Combat_wagon_big.isBoat = false;
         Combat_wagon_big.moveFromBlock = false;
         Combat_wagon_big.inspect_children = false;
         Combat_wagon_big.inspect_experience = true;
         Combat_wagon_big.disableJumpAnimation = true;
         Combat_wagon_big.canBeCitizen = true;
         Combat_wagon_big.inspect_kills = true;
		 Combat_wagon_big.damagedByOcean = true;
         Combat_wagon_big.use_items = false;
         Combat_wagon_big.oceanCreature = false;
         Combat_wagon_big.take_items = false;
         Combat_wagon_big.tech = "Siegeweapons";
         Combat_wagon_big.defaultAttack = "WagonBala";
         Combat_wagon_big.nameLocale = "Combat_wagon_big"; 
         Combat_wagon_big.nameTemplate = "Asedio_Names";
         Combat_wagon_big.job = "attacker";
         Combat_wagon_big.icon = "iconCombat_wagon_big";
         AssetManager.actor_library.CallMethod("loadShadow", Combat_wagon_big);
         Combat_wagon_big.animation_idle = "idle_0";
         Combat_wagon_big.animation_walk = "walk_0,walk_1,walk_2,walk_3";
         Combat_wagon_big.animation_swim = "swim_0,swim_1";
         Combat_wagon_big.actorSize = ActorSize.S17_Dragon;
         Combat_wagon_big.texture_path = "Combat_wagon_big";
         AssetManager.actor_library.addColorSet("FFFColor");
         Localization.addLocalization(Combat_wagon_big.nameLocale, Combat_wagon_big.nameLocale);
         AssetManager.actor_library.add(Combat_wagon_big);
		 AssetManager.actor_library.CallMethod("addTrait", "immortal");
         Combat_wagon_big.color = Toolbox.makeColor("#33826D");
		 
         var Combat_wagon_small = AssetManager.actor_library.clone("Combat_wagon_small", "_mob");
         Combat_wagon_small.race = "human";
         Combat_wagon_small.kingdom = "human";
         Combat_wagon_small.base_stats[S.attack_speed] = 190f;
         Combat_wagon_small.base_stats[S.accuracy] = 70f;
         Combat_wagon_small.base_stats[S.health] = 300;
		 Combat_wagon_small.base_stats[S.scale] = 0.22f;
         Combat_wagon_small.base_stats[S.speed] = 10f;
		 Combat_wagon_small.base_stats[S.range] = 9;
         Combat_wagon_small.base_stats[S.damage] = 50;
		 Combat_wagon_small.base_stats[S.fertility] = -1.0f;
         Combat_wagon_small.base_stats[S.knockback_reduction] = 1.0f;
         Combat_wagon_small.base_stats[S.armor] = 40;
         Combat_wagon_small.skipFightLogic = false;
         Combat_wagon_small.inspect_stats = true;
         Combat_wagon_small.landCreature = true;
         Combat_wagon_small.inspect_home = true;
         Combat_wagon_small.drawBoatMark = true;
         Combat_wagon_small.flying = false;
         Combat_wagon_small.needFood = false;
         Combat_wagon_small.can_edit_traits = false;
         Combat_wagon_small.canReceiveTraits = false;
         Combat_wagon_small.very_high_flyer = false;
         Combat_wagon_small.isBoat = false;
         Combat_wagon_small.moveFromBlock = false;
         Combat_wagon_small.inspect_children = false;
         Combat_wagon_small.inspect_experience = true;
         Combat_wagon_small.disableJumpAnimation = true;
         Combat_wagon_small.canBeCitizen = true;
         Combat_wagon_small.inspect_kills = true;
		 Combat_wagon_small.damagedByOcean = true;
         Combat_wagon_small.use_items = false;
         Combat_wagon_small.oceanCreature = false;
         Combat_wagon_small.take_items = false;
         Combat_wagon_small.tech = "Siegeweapons";
         Combat_wagon_small.defaultAttack = "WagonBala";
         Combat_wagon_small.nameLocale = "Combat_wagon_small"; 
         Combat_wagon_small.nameTemplate = "Asedio_Names";
         Combat_wagon_small.job = "attacker";
         Combat_wagon_small.icon = "iconCombat_wagon_small";
         AssetManager.actor_library.CallMethod("loadShadow", Combat_wagon_small);
         Combat_wagon_small.animation_idle = "idle_0";
         Combat_wagon_small.animation_walk = "walk_0,walk_1,walk_2,walk_3";
         Combat_wagon_small.animation_swim = "swim_0,swim_1";
         Combat_wagon_small.actorSize = ActorSize.S17_Dragon;
         Combat_wagon_small.texture_path = "Combat_wagon_small";
         AssetManager.actor_library.addColorSet("FFFColor");
         Localization.addLocalization(Combat_wagon_small.nameLocale, Combat_wagon_small.nameLocale);
         AssetManager.actor_library.add(Combat_wagon_small);
		 AssetManager.actor_library.CallMethod("addTrait", "immortal");
         Combat_wagon_small.color = Toolbox.makeColor("#33826D");
		 
         var War_Mortar = AssetManager.actor_library.clone("War_Mortar", "_mob");
         War_Mortar.race = "human";
         War_Mortar.kingdom = "human";
         War_Mortar.base_stats[S.attack_speed] = 1f;
         War_Mortar.base_stats[S.accuracy] = 100f;
         War_Mortar.base_stats[S.health] = 360;
		 War_Mortar.base_stats[S.scale] = 0.18f;
         War_Mortar.base_stats[S.speed] = 10f;
		 War_Mortar.base_stats[S.range] = 10;
         War_Mortar.base_stats[S.damage] = 400;
		 War_Mortar.base_stats[S.fertility] = -1.0f;
         War_Mortar.base_stats[S.knockback_reduction] = 1.0f;
         War_Mortar.base_stats[S.armor] = 45;
         War_Mortar.skipFightLogic = false;
         War_Mortar.inspect_stats = true;
         War_Mortar.landCreature = true;
         War_Mortar.inspect_home = true;
         War_Mortar.drawBoatMark = true;
         War_Mortar.flying = false;
         War_Mortar.needFood = false;
         War_Mortar.can_edit_traits = false;
         War_Mortar.canReceiveTraits = false;
         War_Mortar.very_high_flyer = false;
         War_Mortar.isBoat = false;
         War_Mortar.moveFromBlock = false;
         War_Mortar.inspect_children = false;
         War_Mortar.inspect_experience = true;
         War_Mortar.disableJumpAnimation = true;
         War_Mortar.canBeCitizen = true;
         War_Mortar.inspect_kills = true;
		 War_Mortar.damagedByOcean = true;
         War_Mortar.use_items = false;
         War_Mortar.oceanCreature = false;
         War_Mortar.take_items = false;
         War_Mortar.tech = "Siegeweapons";
         War_Mortar.defaultAttack = "mortarAtt";
         War_Mortar.nameLocale = "War_Mortar"; 
         War_Mortar.nameTemplate = "Asedio_Names";
         War_Mortar.job = "attacker";
         War_Mortar.icon = "iconWar_Mortar";
         AssetManager.actor_library.CallMethod("loadShadow", War_Mortar);
         War_Mortar.animation_idle = "idle_0";
         War_Mortar.animation_walk = "walk_0,walk_1,walk_2,walk_3";
         War_Mortar.animation_swim = "swim_0,swim_1";
         War_Mortar.actorSize = ActorSize.S17_Dragon;
         War_Mortar.texture_path = "War_Mortar";
         AssetManager.actor_library.addColorSet("FFFColor");
         Localization.addLocalization(War_Mortar.nameLocale, War_Mortar.nameLocale);
         AssetManager.actor_library.add(War_Mortar);
		 AssetManager.actor_library.CallMethod("addTrait", "immortal");
         War_Mortar.color = Toolbox.makeColor("#33826D"); 
		 
         var Battering_Ram = AssetManager.actor_library.clone("Battering_Ram", "_mob");
         Battering_Ram.race = "human";
         Battering_Ram.kingdom = "human";
         Battering_Ram.base_stats[S.attack_speed] = 1f;
         Battering_Ram.base_stats[S.health] = 300;
		 Battering_Ram.base_stats[S.scale] = 0.18f;
         Battering_Ram.base_stats[S.speed] = 12f;
		 Battering_Ram.base_stats[S.range] = 1;
         Battering_Ram.base_stats[S.damage] = 4000;
		 Battering_Ram.base_stats[S.fertility] = -1.0f;
         Battering_Ram.base_stats[S.knockback_reduction] = 1.0f;
         Battering_Ram.base_stats[S.armor] = 70;
         Battering_Ram.skipFightLogic = false;
         Battering_Ram.inspect_stats = true;
         Battering_Ram.landCreature = true;
         Battering_Ram.inspect_home = true;
         Battering_Ram.drawBoatMark = true;
         Battering_Ram.flying = false;
         Battering_Ram.needFood = false;
         Battering_Ram.can_edit_traits = false;
         Battering_Ram.canReceiveTraits = false;
         Battering_Ram.very_high_flyer = false;
         Battering_Ram.isBoat = false;
         Battering_Ram.moveFromBlock = false;
         Battering_Ram.inspect_children = false;
         Battering_Ram.inspect_experience = true;
         Battering_Ram.disableJumpAnimation = true;
         Battering_Ram.canBeCitizen = true;
         Battering_Ram.inspect_kills = true;
		 Battering_Ram.damagedByOcean = true;
         Battering_Ram.use_items = false;
         Battering_Ram.oceanCreature = false;
         Battering_Ram.take_items = false;
         Battering_Ram.tech = "Siegeweapons";
         Battering_Ram.nameLocale = "Battering_Ram"; 
         Battering_Ram.nameTemplate = "Asedio_Names";
         Battering_Ram.job = "attacker";
         Battering_Ram.icon = "iconBattering_Ram";
         AssetManager.actor_library.CallMethod("loadShadow", Battering_Ram);
         Battering_Ram.animation_idle = "idle_0";
         Battering_Ram.animation_walk = "walk_0,walk_1,walk_2,walk_3";
         Battering_Ram.animation_swim = "swim_0,swim_1";
         Battering_Ram.actorSize = ActorSize.S17_Dragon;
         Battering_Ram.texture_path = "Battering_Ram";
         AssetManager.actor_library.addColorSet("FFFColor");
         Localization.addLocalization(Battering_Ram.nameLocale, Battering_Ram.nameLocale);
         AssetManager.actor_library.add(Battering_Ram);
		 AssetManager.actor_library.CallMethod("addTrait", "immortal");
         Battering_Ram.color = Toolbox.makeColor("#33826D"); 
         
         
		 
        }
    }
}
